config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  # devise_for :users

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  as :user do
    # sessions
    get    'login',  to: 'devise/sessions#new',           as: :new_user_session
    post   'login',  to: 'devise/sessions#create',        as: :user_session
    delete 'logout', to: 'devise/sessions#destroy',       as: :destroy_user_session

    # registrations
    get 'cancel', to: 'devise/registrations#cancel',      as: :cancel_user_registration
    get 'sign_up', to: 'devise/registrations#new',        as: :new_user_registration
    get 'edit', to: 'devise/registrations#edit',          as: :edit_user_registration
    patch 'users', to: 'devise/registrations#update',     as: :user_registration
    put 'users', to: 'devise/registrations#update'
    delete 'users', to: 'devise/registrations#destroy'
    post 'users', to: 'devise/registrations#create'

    # passwords
    get   'password/new',  to: 'devise/passwords#new',    as: :new_user_password
    get   'password/edit', to: 'devise/passwords#edit',   as: :edit_user_password
    patch 'password', to: 'devise/passwords#update',      as: :user_password
    post  'password',  to: 'devise/passwords#create'
    put   'password', to: 'devise/passwords#update'

    # user disc details
    get "/user_details", to: "disc_details#general_details", as: :details_of_user
    post "/user_details" => "disc_details#general_details"

    # error for edisk_directory
    get "/error", to: "edisk_directories#wrong_id", as: :wrong_id
  end


  # get "edisk_directory/:id/new", to: "edisk_directory#new"

  # get "edisk_directory/:id/edit", to: "edisk_directory#edit"
  # post "edisk_directory/:id/edit", to: "edisk_directory#update"

  # delete "edisk_directories/:id/destroy", to:"edisk_directory#destroy"
  resources :edisk_directories
  post "/edisk_directories/new(.:format)", to: "edisk_directories#create"
  # post "/edisk_directory/new", to: "edisk_directory#create"
  # post "/edisk_directory/:id", to: "edisk_directory#create"

  # post "/edisk_directory/:id/edit", to:"edisk_directory#update"
  post "/edisk_files/new(.:format)", to: "edisk_files#create"
  resources :edisk_files
  # post "/edisk_file/:id/edit", to:"edisk_file#update"

  # admin
  as :admin do
    get '/ed-admin' => 'admin#dashboard', as: :admin_dashboard
    delete "/ed-admin/:id" => 'admin#destroy', as: :admin_dashboard2
  end
  # match '*path' => 'edisk_directories#wrong_id', via: :all

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<%#is_there_base_directory2?%>
<header class="header masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0 header-animation">Share your files</h1>
      <h2 class="masthead-subheading mb-0 header-animation">with the whole world</h2>
      <%if user_signed_in?%>
        <%#=  button_to "Open Drive", edisk_directory_path(EdiskDirectory.find(0)), method: :get, class: "btn btn-primary btn-xl rounded-pill mt-5" %>
        <%=  button_to "Open Drive", edisk_directory_path(EdiskDirectory.where(user_id: current_user.id).find_by(name: "home", ancestry: nil)), method: :get, class: "btn btn-primary btn-xl rounded-pill mt-5" %>
    <%else %>
        <%= link_to "Create Account", new_user_registration_path, class: "btn btn-primary btn-xl rounded-pill mt-5" %>
      <%end %>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<footer class="footer, py-3 bg-light fixed-bottom">
    <p class="text-center", style="margin: 0">Made with ❤ by 🧑‍🚀 Mateusz Białowąs |🦸‍♂️ Maciej Bociuk | 👨‍💻 Mateusz Sekściński</p>
</footer>