config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  # devise_for :users

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  as :user do
    # sessions
    get    'login',  to: 'devise/sessions#new',           as: :new_user_session
    post   'login',  to: 'devise/sessions#create',        as: :user_session
    delete 'logout', to: 'devise/sessions#destroy',       as: :destroy_user_session

    # registrations
    get 'cancel', to: 'devise/registrations#cancel',      as: :cancel_user_registration
    get 'sign_up', to: 'devise/registrations#new',        as: :new_user_registration
    get 'edit', to: 'devise/registrations#edit',          as: :edit_user_registration
    patch 'users', to: 'devise/registrations#update',     as: :user_registration
    put 'users', to: 'devise/registrations#update'
    delete 'users', to: 'devise/registrations#destroy'
    post 'users', to: 'devise/registrations#create'

    # passwords
    get   'password/new',  to: 'devise/passwords#new',    as: :new_user_password
    get   'password/edit', to: 'devise/passwords#edit',   as: :edit_user_password
    patch 'password', to: 'devise/passwords#update',      as: :user_password
    post  'password',  to: 'devise/passwords#create'
    put   'password', to: 'devise/passwords#update'

    # user disc details
    get "/user_details", to: "disc_details#general_details", as: :details_of_user
    post "/user_details" => "disc_details#general_details"

    # error for edisk_directory
    get "/error", to: "edisk_directories#wrong_id", as: :wrong_id
  end


  # get "edisk_directory/:id/new", to: "edisk_directory#new"

  # get "edisk_directory/:id/edit", to: "edisk_directory#edit"
  # post "edisk_directory/:id/edit", to: "edisk_directory#update"

  # delete "edisk_directories/:id/destroy", to:"edisk_directory#destroy"
  resources :edisk_directories
  post "/edisk_directories/new(.:format)", to: "edisk_directories#create"
  # post "/edisk_directory/new", to: "edisk_directory#create"
  # post "/edisk_directory/:id", to: "edisk_directory#create"

  # post "/edisk_directory/:id/edit", to:"edisk_directory#update"
  post "/edisk_files/new(.:format)", to: "edisk_files#create"
  resources :edisk_files
  # post "/edisk_file/:id/edit", to:"edisk_file#update"

  # admin
  as :admin do
    get '/ed-admin' => 'admin#dashboard', as: :admin_dashboard
    delete "/ed-admin/:id" => 'admin#destroy', as: :admin_dashboard2
  end
  # match '*path' => 'edisk_directories#wrong_id', via: :all

end

app/views/shared/_flash.html.erb
<% if flash.alert %>
    <div class="container mt-5 position-absolute start-50 top-0 translate-middle" style="z-index: 1000">
      <div class="alert alert-warning flash-animation" role="alert">
        <%= flash.alert %>
      </div>
    </div>
  <% end %>


  <% if flash.notice %>
    <div class="container mt-5 position-absolute start-50 top-0 translate-middle" style="z-index: 1000">
      <div class="alert alert-info flash-animation" role="alert">
        <%= flash.notice %>
      </div>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <a class="navbar-brand cloud-logo d-flex"  href="<%= root_path %>">
      <svg height="50" viewBox="0 0 122 105" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M62.3181 0.0630151C32.7181 -1.53698 28.6514 27.7297 30.3181 42.563L43.3181 44.563C43.3181 22.063 43.8181 13.063 62.3181 12.063C77.1181 11.263 80.3181 26.063 79.3181 29.063L91.8181 38.563C94.3181 26.3963 91.9181 1.66302 62.3181 0.0630151Z" fill="#53607A"/>
        <path d="M45.5835 44.2048C26.7835 31.8048 20.0835 48.0381 19.0835 57.7048C13.2502 59.8714 1.28349 67.3048 0.0834859 79.7048C-1.11651 92.1048 10.9168 100.871 17.0835 103.705C43.7502 104.538 98.0835 105.705 102.083 103.705C107.083 101.205 120.083 97.7048 121.083 79.7048C121.883 65.3048 108.75 58.0381 102.083 56.2048C102.583 48.0381 98.7835 30.7048 79.5835 26.7048C60.3835 22.7048 48.9168 36.7048 45.5835 44.2048Z" fill="#0B4DC8"/>
        <path d="M61.5 56L75 66.5H67.515L67.5 83H55.5V66.5H48L61.5 56Z" fill="white"/>
      </svg>
      <%= link_to "Edisk", root_path, class: "navbar-brand text-logo" %>
<!--      <a class="navbar-brand text-logo" href="<%#=root_path %>">Edisk</a>-->
    </a>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item d-flex">
          <%= link_to "Github", "https://github.com/mateuszbialowas/Edisk-Rails", class: "nav-link active" %>
          <a href="https://github.com/mateuszbialowas/Edisk-Rails" class="nav-link active">
            <i class="fab fa-github"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in?%>
          <li class="nav-item ">
            <%= link_to current_user.username, details_of_user_path, class: "nav-link me-5 username"%>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary ml-4 nav-button", type: "button" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbarmain.html.erb
<nav class="navbar navbar-expand-lg navbar-light d-flex", id="navbar-main">
  <div class="container-fluid">

    <a class="navbar-brand cloud-logo d-flex"  href="<%= root_path %>">
      <svg height="50" viewBox="0 0 122 105" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M62.3181 0.0630151C32.7181 -1.53698 28.6514 27.7297 30.3181 42.563L43.3181 44.563C43.3181 22.063 43.8181 13.063 62.3181 12.063C77.1181 11.263 80.3181 26.063 79.3181 29.063L91.8181 38.563C94.3181 26.3963 91.9181 1.66302 62.3181 0.0630151Z" fill="#53607A"/>
        <path d="M45.5835 44.2048C26.7835 31.8048 20.0835 48.0381 19.0835 57.7048C13.2502 59.8714 1.28349 67.3048 0.0834859 79.7048C-1.11651 92.1048 10.9168 100.871 17.0835 103.705C43.7502 104.538 98.0835 105.705 102.083 103.705C107.083 101.205 120.083 97.7048 121.083 79.7048C121.883 65.3048 108.75 58.0381 102.083 56.2048C102.583 48.0381 98.7835 30.7048 79.5835 26.7048C60.3835 22.7048 48.9168 36.7048 45.5835 44.2048Z" fill="#0B4DC8"/>
        <path d="M61.5 56L75 66.5H67.515L67.5 83H55.5V66.5H48L61.5 56Z" fill="white"/>
      </svg>
      <%= link_to "Edisk", root_path, class: "navbar-brand text-logo" %>
      <!--      <a class="navbar-brand text-logo" href="<%#=root_path %>">Edisk</a>-->
    </a>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item d-flex">
          <%= link_to "Github", "https://github.com/mateuszbialowas/Edisk-Rails", class: "nav-link active" %>
          <a href="https://github.com/mateuszbialowas/Edisk-Rails" class="nav-link active">
            <i class="fab fa-github"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in?%>
          <li class="nav-item ">
            <%= link_to current_user.username, details_of_user_path, class: "nav-link me-5", id: "username-navbar" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary ml-4 nav-button", type: "button" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>