config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  # devise_for :users

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  as :user do
    # sessions
    get    'login',  to: 'devise/sessions#new',           as: :new_user_session
    post   'login',  to: 'devise/sessions#create',        as: :user_session
    delete 'logout', to: 'devise/sessions#destroy',       as: :destroy_user_session

    # registrations
    get 'cancel', to: 'devise/registrations#cancel',      as: :cancel_user_registration
    get 'sign_up', to: 'devise/registrations#new',        as: :new_user_registration
    get 'edit', to: 'devise/registrations#edit',          as: :edit_user_registration
    patch 'users', to: 'devise/registrations#update',     as: :user_registration
    put 'users', to: 'devise/registrations#update'
    delete 'users', to: 'devise/registrations#destroy'
    post 'users', to: 'devise/registrations#create'

    # passwords
    get   'password/new',  to: 'devise/passwords#new',    as: :new_user_password
    get   'password/edit', to: 'devise/passwords#edit',   as: :edit_user_password
    patch 'password', to: 'devise/passwords#update',      as: :user_password
    post  'password',  to: 'devise/passwords#create'
    put   'password', to: 'devise/passwords#update'

    # user disc details
    get "/user_details", to: "disc_details#general_details", as: :details_of_user
    post "/user_details" => "disc_details#general_details"

    # error for edisk_directory
    get "/error", to: "edisk_directories#wrong_id", as: :wrong_id
  end


  # get "edisk_directory/:id/new", to: "edisk_directory#new"

  # get "edisk_directory/:id/edit", to: "edisk_directory#edit"
  # post "edisk_directory/:id/edit", to: "edisk_directory#update"

  # delete "edisk_directories/:id/destroy", to:"edisk_directory#destroy"
  resources :edisk_directories
  post "/edisk_directories/new(.:format)", to: "edisk_directories#create"
  # post "/edisk_directory/new", to: "edisk_directory#create"
  # post "/edisk_directory/:id", to: "edisk_directory#create"

  # post "/edisk_directory/:id/edit", to:"edisk_directory#update"
  post "/edisk_files/new(.:format)", to: "edisk_files#create"
  resources :edisk_files
  # post "/edisk_file/:id/edit", to:"edisk_file#update"

  # admin
  as :admin do
    get '/ed-admin' => 'admin#dashboard', as: :admin_dashboard
    delete "/ed-admin/:id" => 'admin#destroy', as: :admin_dashboard2
  end
  # match '*path' => 'edisk_directories#wrong_id', via: :all

end

app/models/edisk_directory.rb
class EdiskDirectory < ApplicationRecord

  belongs_to :user
  has_many :edisk_files, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: {scope: [:ancestry,  :user_id]}
  has_ancestry

  def ancestry_into_array
    a = ancestry.to_s.split("/")
    @text = ""
    a.each do |temp|
      @text += EdiskDirectory.find(temp.to_i).name
      @text += "/"
    end
    @text += name
  end

end

app/controllers/edisk_directories_controller.rb
class EdiskDirectoriesController < ApplicationController
  before_action :authenticate_user!

  rescue_from ::ActiveRecord::RecordNotFound, with: :record_not_found
  helper_method :return_all_files_from_directory, :expiration_time_into_string

  after_action :count_Size_for_user

  #wrzutka testowa
  before_action :set_breadcrumbs

  #
  def new
    @query = params[:format]
    @edisk_directory = EdiskDirectory.new
  end

  def create
    @query = params[:format]
    @edisk_directory = current_user.edisk_directories.children_of(params[:parent_id]).new(edisk_directory_params)
    actual_dir = EdiskDirectory.where(user_id: current_user.id).find(@edisk_directory.parent_id)
    if @edisk_directory.save
      redirect_to edisk_directory_path(actual_dir)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @edisk_directory = EdiskDirectory.where(user_id: current_user.id).find(params[:id])
  end

  def update
      @edisk_directory = EdiskDirectory.where(user_id: current_user.id).find(params[:id])
      actual_dir = EdiskDirectory.where(user_id: current_user.id).find(@edisk_directory.parent_id)

      if @edisk_directory.update(edisk_directory_params)
        redirect_to edisk_directory_path(actual_dir)
      else
        render :edit, status: :unprocessable_entity
      end
  end
  def destroy
    @edisk_directory = EdiskDirectory.where(user_id: current_user.id).find(params[:id])

    if @edisk_directory.ancestry.nil?
      redirect_to edisk_directory_path(@edisk_directory), alert: "You cannot do that. Stop it"
    else
      actual_dir = @edisk_directory.parent_id
      @edisk_directory.destroy

      redirect_to edisk_directory_path(actual_dir), notice: "Sucesfully destroyed"

    end
  end
  def show
    @edisk_directory = EdiskDirectory.find(params[:id])
    @edisk_directories = EdiskDirectory.children_of(@edisk_directory).where(user_id: current_user.id)

    #wrztuka
    @curr_path
    @rev_bread = ""
    @mini_root = @edisk_directory
    while !@mini_root.parent_id.nil? do
      @rev_bread = @mini_root.name + @rev_bread
      @rev_bread = "/" + @rev_bread
      @mini_root = @mini_root.parent
    end
    add_breadcrumbs('My disc', "/edisk_directories/"+@mini_root.id.to_s) #strona uzytkownika
    @abc = @rev_bread.split('/')
    @abc.each_index do |x|
      if !@abc[x].eql? ""
        @curr_id = EdiskDirectory.where(name: @abc[x], user_id: current_user.id)
        @curr_ids = @curr_id.ids.to_s
        @curr_ids[0] = ''
        @curr_ids = @curr_ids.chomp("]")
        @curr_path = "/edisk_directories/"+@curr_ids
        add_breadcrumbs(@abc[x], @curr_path)
      end
    end
  end

  def count_Size_for_user
    temp = 0
    EdiskFile.where(userID: current_user.id).each do |f|
      temp += f.efile.byte_size
    end
    current_user.update_attribute :current_size, temp
  end

  def expiration_time_into_string(expiration_time)
    @returning = ''
    case expiration_time
    when "nil"
      @returning = "Someday"
    else
      @returning = expiration_time
    end
  end

  def add_breadcrumbs(label, path = nil)
    @breadcrumbs << {
      label: label,
      path: path
    }
  end
  def set_breadcrumbs
    @breadcrumbs = []
  end
  # koneic wrzutki


  def return_all_files_from_directory(file_ed)
    @edisk_file = EdiskFile.where(edisk_directory_id: file_ed.id)
  end

  #start
  def record_not_found(exception)
    redirect_to wrong_id_path, alert: "That site does not exists, wrong id"
  end
  #koniec

  private
  def edisk_directory_params
    params.require(:edisk_directory).permit( :name,:parent_id, :ancestry)
  end

  end

app/views/edisk_directories/edit.html.erb
<section class="col-8 offset-2 col-sm-6 offset-sm-3">
  <h5>Edit directory </h5>

  <%= form_with model: @edisk_directory do |f| %>
  <div class="field, form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, value: @edisk_directory.name, placeholder: @edisk_directory.name, class: "form-control mb-2"%>
    <% if @edisk_directory.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @edisk_directory.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% %>
  <div>

    <%= f.label :path %>
    <%= f.collection_select :parent_id, EdiskDirectory.all.where(user_id: current_user.id).excluding(EdiskDirectory.descendants_of(@edisk_directory.id)).excluding(@edisk_directory), :id, :ancestry_into_array, {:selected => @edisk_directory.parent_id} %>

  </div>

  <%= f.submit "Confirm" %>

<% end %>
</section>

app/views/edisk_directories/index.html.erb
<h1>Dokumenciki</h1>

<ul>
  <% @edisk_directory.each do |directory| %>
    <li>
      <%= directory.name %>
    </li>
  <% end %>
</ul>

app/views/edisk_directories/new.html.erb
<section class="col-8 offset-2 col-sm-6 offset-sm-3">
  <h5>Create new directory </h5>
  <%= form_with model: @edisk_directory, url: new_edisk_directory_path(format: @query) do |f| %>

    <% if @edisk_directory.errors.any? %>
    <div class = "alert alert-danger">
      <%@edisk_directory.errors.full_messages.each do |message| %>
        <div> <%=message %> </div>
      <%end%>
    </div>
  <%end%>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control mb-2" %>
    </div>
  <div>
  <%= hidden_field_tag :parent_id, "#{params[:format]}" %>
    <%= hidden_field_tag :@query, "#{@query}" %>
  </div>
  <%= f.submit "Confirm" %>

<% end %>
</section>

app/views/edisk_directories/show.html.erb
<style>
    *{
        box-sizing: border-box;
    }

    .center {
        margin-left: auto;
        margin-right: auto;
    }
    .card-style{
        margin: 15px;
    }

    @media only screen and (min-width: 1201px){
        .card-style{
            width: 22%;
            margin: 10px;
        }
    }


    @media only screen and (max-width: 1200px){
        .card-style{
            width: 30%;
            margin: 10px;
        }
    }

    @media only screen and (max-width: 992px){
        .card-style{
            width: 45%;
            margin: 10px;
        }
    }

    @media only screen and (max-width: 576px){
        .card-style{
            width: 60%;

        }
    }
    .dropbtn {
        background-color: #3498DB;
        color: white;
        padding: 13px;
        font-size: 13px;
        border: none;
        cursor: pointer;
    }

    .dropbtn:hover, .dropbtn:focus {
        background-color: #2980B9;
    }

    .dropdown {
        float: right;
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        overflow: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

  .dropdown a:hover {background-color: #ddd;}

  .show {display: block;}
</style>
<script>
    /* When the user clicks on the button,
    toggle between hiding and showing the dropdown content */
    function myFunction(number) {
        console.log(number)
        var x = document.getElementById("myDropdown" + number).classList.toggle('show');
    }
    function myFunction_directory(number) {
        console.log(number)
        var x = document.getElementById("myDropdown_directory" + number).classList.toggle('show');
    }
    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

<% @current_directory = EdiskDirectory.find(params[:id]) %>

<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <div class="card">
                <div class="card-header">
                  <div>
                    <table class="center">
                      <tr>
                        <td>
                          Directory panel:
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
                <div class="card-body">
                  <div>
                    <p>Add new directory<%=button_to "+", new_edisk_directory_path(@current_directory), method: :get, class: "btn btn-success btn"%></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card">
                <div class="card-header">
                  <div>
                    <table class="center">
                      <tr>
                        <td>
                          File uploading panel:
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
                <div class="card-body">
                  <div>
                    <p>Upload file:<%=button_to "+", new_edisk_file_path(@current_directory), method: :get, class: "btn btn-warning btn"%></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card-header">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <% @breadcrumbs.each do |breadcrumb| %>
                <% if breadcrumb[:path].nil? %>
                  <li class="beadcrump-item active" aria-current="page">
                    <%= breadcrumb[:label] %>
                  </li>
                <% else %>
                  <li class="breadcrumb-item">
                    <%= link_to breadcrumb[:label], breadcrumb[:path] %>
                  </li>
                <% end %>
              <% end %>
            </ol>
          </nav>
        </div>
        <div class="card-body">
          <div class="card">
            <div class="card-body">
              <div class="container d-flex flex-wrap d-flex justify-content-evenly">
                <% @edisk_directories.each_with_index do |post, index| %>
                  <div class="col-sm-6 col-lg-4">
                    <div class="card" style="width: 15rem;">
                      <%#= image_pack_tag %>
                      <%= image_pack_tag 'file.png', style: "", alt: "Card image cap", class: "card-img-top"  %>
<!--                      <img class="card-img-top" src="/assets/file.png" alt="Card image cap" style="max-height: 300px; max-width: 238.4px; min-height: 300px; min-width: 238.4px;">-->
                      <div class="card-body">
                        <h5 class="card-title"><%=link_to post.name, edisk_directory_path(post)%></h5>
                          <div class="dropdown">
                            <button onclick="myFunction_directory(<%=index%>)" class="dropbtn">Options</button>
                            <div id="myDropdown_directory<%=index%>" class="dropdown-content">
                              <%= link_to "Edit", edit_edisk_directory_path(post), method: :get%>
                              <%= link_to "Delete", edisk_directory_path(post), method: :delete,data: {confirm: "Are you sure?"}%>
                            </div>
                          </div>
                      </div>
                  </div>
                <% end %>
              </div>
              <div class="container d-flex flex-wrap d-flex justify-content-evenly">
                <% return_all_files_from_directory(@current_directory).each_with_index do |post, index| %>
                  <div class="col-sm-6 col-lg-4">
                    <div class="card" style="width: 15rem;">
                      <%if post.efile.video? %>
                        <%= video_tag(url_for(post.efile), class:"card-img-top", :controls => true, style:"max-height: 300px; max-width: 238.4px; min-height: 300px; min-width: 238.4px;") %>
                      <%elsif post.efile.previewable? %>
                        <%= image_tag url_for(post.efile.preview(resize_to_limit: [1000, 1000])), class:"card-img-top", style:"max-height: 300px; max-width: 238.4px; min-height: 300px; min-width: 238.4px;"%>
                      <%elsif post.efile.image? %>
                        <%= image_tag url_for(post.efile), class:"card-img-top", style:"max-height: 300px; max-width: 238.4px; min-height: 300px; min-width: 238.4px;"%>
                      <% else %>
                        <%= link_to rails_blob_url(post.efile, disposition: "attachment") do %>
                          <%= image_pack_tag "#{post.pic_for_type}", alt: "Download file", class: "card-img-top", style:"max-height: 300px; max-width: 238.4px; min-height: 300px; min-width: 238.4px;" %>
                        <%end %>
                      <%end %>
                      <div class="card-body">
                        <h5 class="card-title"> <%=link_to post.name, post.efile %></h5>
                        <div>
                          <div class="dropdown">
                            <button onclick="myFunction(<%=index%>)" class="dropbtn">Options</button>
                            <div id="myDropdown<%=index%>" class="dropdown-content">
                              <%=link_to "Edit",  edit_edisk_file_path(post), method: :get%>
                              <%=link_to "Delete", edisk_file_path(post), method: :delete, data: {confirm: "Are you sure?"}%>
                              <%=link_to "Expire all links", edisk_file_path(post), method: :get %>
                            </div>
                          </div>
                          <p><%="Link expires in:"%></p>
                           <p><%= expiration_time_into_string(post.expiration_time)%></p>
                          <% if post.expiration_time == "nil" %>
                            <%= text_field_tag "#{post.name}", "#{post.efile.url}" %>
                          <%else %>
                            <%= text_field_tag "#{post.name}", "#{post.efile.url(expires_in: post.expiration_time.to_i)}" %>
                          <%end %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </script>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/edisk_directories/wrong_id.erb
<style>
  .center {
      border: 5px solid #EFEFEF;
      text-align: center;
      background-image: url('https://images.gamebanana.com/img/ico/sprays/603980092d87f.png');
      background-repeat: no-repeat;
      background-attachment: inherit;
  }
</style>

<div class="container-fluid">
  <div class="card, center">
    <div class="card-body">
      <h2>Page you are looking for, does not exist</h2>
      <h5>Please consider checking url for typo</h5>
    </div>
    <div class="card-body">
        <p>
          Return to your disc here:         <%=  button_to "Open Drive", edisk_directory_path(EdiskDirectory.where(user_id: current_user.id).find_by(name: "home", ancestry: nil)), method: :get, class: "d-none d-sm-inline btn btn-primary mx-2" %>
        </p>

    </div>
  </div>
</div>